In [1]:
# Diabetes

In [2]:
import pandas as pd 

In [3]:
# Pipeline

In [4]:
from sklearn.pipeline import Pipeline
import pipeline_utilities_scrap as p_util
from pipeline_utilities_scrap import X_y_set
import glob

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
# X_feature_set() includes loading data, spliting X_train, X_test and y_train, y_test.
X_train, X_test, y_train, y_test = X_y_set()
                                                    

Loading the DataFrame...


Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0                0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1                0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2                0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3                0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4                0.0     1.0       1.0        1.0  24.0     0.0     0.0   
...              ...     ...       ...        ...   ...     ...     ...   
253675           0.0     1.0       1.0        1.0  45.0     0.0     0.0   
253676           2.0     1.0       1.0        1.0  18.0     0.0     0.0   
253677           0.0     0.0       0.0        1.0  28.0     0.0     0.0   
253678           0.0     1.0       0.0        1.0  23.0     0.0     0.0   
253679           2.0     1.0       1.0        1.0  25.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                        0.0           0.0     0.0  ...            1.0   
1                        0.0           1.0     0.0  ...            0.0   
2                        0.0           0.0     1.0  ...            1.0   
3                        0.0           1.0     1.0  ...            1.0   
4                        0.0           1.0     1.0  ...            1.0   
...                      ...           ...     ...  ...            ...   
253675                   0.0           0.0     1.0  ...            1.0   
253676                   0.0           0.0     0.0  ...            1.0   
253677                   0.0           1.0     1.0  ...            1.0   
253678                   0.0           0.0     1.0  ...            1.0   
253679                   1.0           1.0     1.0  ...            1.0   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
0               0.0      5.0      18.0      15.0       1.0  0.0   9.0   
1               1.0      3.0       0.0       0.0       0.0  0.0   7.0   
2               1.0      5.0      30.0      30.0       1.0  0.0   9.0   
3               0.0      2.0       0.0       0.0       0.0  0.0  11.0   
4               0.0      2.0       3.0       0.0       0.0  0.0  11.0   
...             ...      ...       ...       ...       ...  ...   ...   
253675          0.0      3.0       0.0       5.0       0.0  1.0   5.0   
253676          0.0      4.0       0.0       0.0       1.0  0.0  11.0   
253677          0.0      1.0       0.0       0.0       0.0  0.0   2.0   
253678          0.0      3.0       0.0       0.0       0.0  1.0   7.0   
253679          0.0      2.0       0.0       0.0       0.0  0.0   9.0   

        Education  Income  
0             4.0     3.0  
1             6.0     1.0  
2             4.0     8.0  
3             3.0     6.0  
4             5.0     4.0  
...           ...     ...  
253675        6.0     7.0  
253676        2.0     4.0  
253677        5.0     2.0  
253678        5.0     1.0  
253679        6.0     2.0  

[253680 rows x 22 columns]

'Value Counts'

Diabetes_012
0.0    213703
2.0     35346
1.0      4631
Name: count, dtype: int64

'Shape'

(253680, 22)

Display X below:


HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0          1.0       1.0        1.0  40.0     1.0     0.0   
1          0.0       0.0        0.0  25.0     1.0     0.0   
2          1.0       1.0        1.0  28.0     0.0     0.0   
3          1.0       0.0        1.0  27.0     0.0     0.0   
4          1.0       1.0        1.0  24.0     0.0     0.0   
...        ...       ...        ...   ...     ...     ...   
253675     1.0       1.0        1.0  45.0     0.0     0.0   
253676     1.0       1.0        1.0  18.0     0.0     0.0   
253677     0.0       0.0        1.0  28.0     0.0     0.0   
253678     1.0       0.0        1.0  23.0     0.0     0.0   
253679     1.0       1.0        1.0  25.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
0                        0.0           0.0     0.0      1.0  ...   
1                        0.0           1.0     0.0      0.0  ...   
2                        0.0           0.0     1.0      0.0  ...   
3                        0.0           1.0     1.0      1.0  ...   
4                        0.0           1.0     1.0      1.0  ...   
...                      ...           ...     ...      ...  ...   
253675                   0.0           0.0     1.0      1.0  ...   
253676                   0.0           0.0     0.0      0.0  ...   
253677                   0.0           1.0     1.0      0.0  ...   
253678                   0.0           0.0     1.0      1.0  ...   
253679                   1.0           1.0     1.0      0.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
0                 1.0          0.0      5.0      18.0      15.0       1.0   
1                 0.0          1.0      3.0       0.0       0.0       0.0   
2                 1.0          1.0      5.0      30.0      30.0       1.0   
3                 1.0          0.0      2.0       0.0       0.0       0.0   
4                 1.0          0.0      2.0       3.0       0.0       0.0   
...               ...          ...      ...       ...       ...       ...   
253675            1.0          0.0      3.0       0.0       5.0       0.0   
253676            1.0          0.0      4.0       0.0       0.0       1.0   
253677            1.0          0.0      1.0       0.0       0.0       0.0   
253678            1.0          0.0      3.0       0.0       0.0       0.0   
253679            1.0          0.0      2.0       0.0       0.0       0.0   

        Sex   Age  Education  Income  
0       0.0   9.0        4.0     3.0  
1       0.0   7.0        6.0     1.0  
2       0.0   9.0        4.0     8.0  
3       0.0  11.0        3.0     6.0  
4       0.0  11.0        5.0     4.0  
...     ...   ...        ...     ...  
253675  1.0   5.0        6.0     7.0  
253676  0.0  11.0        2.0     4.0  
253677  0.0   2.0        5.0     2.0  
253678  1.0   7.0        5.0     1.0  
253679  0.0   9.0        6.0     2.0  

[253680 rows x 21 columns]

y


array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [2.]])

X_train


HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
153605     0.0       0.0        1.0  23.0     0.0     0.0   
209016     1.0       0.0        0.0  25.0     1.0     0.0   
24047      0.0       0.0        1.0  23.0     0.0     0.0   
70479      0.0       1.0        1.0  29.0     0.0     0.0   
114169     0.0       0.0        1.0  32.0     0.0     0.0   
...        ...       ...        ...   ...     ...     ...   
229119     0.0       0.0        0.0  20.0     1.0     0.0   
5192       0.0       0.0        1.0  23.0     0.0     0.0   
208780     1.0       1.0        1.0  17.0     1.0     0.0   
229611     1.0       0.0        0.0  30.0     1.0     0.0   
128037     1.0       0.0        1.0  21.0     1.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
153605                   0.0           0.0     1.0      1.0  ...   
209016                   0.0           1.0     0.0      1.0  ...   
24047                    0.0           1.0     1.0      1.0  ...   
70479                    0.0           1.0     0.0      1.0  ...   
114169                   0.0           1.0     0.0      1.0  ...   
...                      ...           ...     ...      ...  ...   
229119                   0.0           0.0     0.0      1.0  ...   
5192                     0.0           0.0     1.0      1.0  ...   
208780                   1.0           1.0     1.0      1.0  ...   
229611                   0.0           1.0     1.0      1.0  ...   
128037                   0.0           1.0     0.0      0.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
153605            1.0          0.0      3.0       0.0       0.0       0.0   
209016            1.0          0.0      4.0       0.0      30.0       1.0   
24047             1.0          0.0      2.0       0.0       0.0       0.0   
70479             1.0          0.0      1.0       0.0       0.0       0.0   
114169            1.0          0.0      1.0       0.0       0.0       0.0   
...               ...          ...      ...       ...       ...       ...   
229119            1.0          1.0      2.0       0.0      10.0       0.0   
5192              1.0          0.0      2.0       0.0       0.0       0.0   
208780            1.0          0.0      5.0       0.0      30.0       0.0   
229611            1.0          0.0      3.0       5.0       0.0       0.0   
128037            1.0          0.0      2.0       0.0       0.0       0.0   

        Sex   Age  Education  Income  
153605  1.0   2.0        6.0     8.0  
209016  1.0   8.0        4.0     7.0  
24047   1.0  10.0        4.0     2.0  
70479   0.0  11.0        6.0     8.0  
114169  1.0   5.0        5.0     7.0  
...     ...   ...        ...     ...  
229119  0.0   5.0        6.0     6.0  
5192    0.0  10.0        6.0     6.0  
208780  0.0  12.0        4.0     3.0  
229611  1.0   6.0        6.0     8.0  
128037  0.0  12.0        6.0     5.0  

[190260 rows x 21 columns]

X_test


HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
235899     1.0       0.0        1.0  23.0     1.0     0.0   
74852      0.0       0.0        1.0  22.0     1.0     0.0   
8205       1.0       1.0        1.0  26.0     1.0     0.0   
127632     1.0       0.0        1.0  39.0     0.0     0.0   
32021      0.0       0.0        1.0  22.0     1.0     0.0   
...        ...       ...        ...   ...     ...     ...   
108360     0.0       1.0        1.0  29.0     1.0     0.0   
8531       1.0       0.0        1.0  24.0     1.0     0.0   
183429     1.0       1.0        1.0  31.0     0.0     0.0   
52932      0.0       0.0        1.0  32.0     1.0     0.0   
94566      1.0       0.0        1.0  27.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  Veggies  ...  \
235899                   0.0           1.0     1.0      1.0  ...   
74852                    1.0           1.0     1.0      1.0  ...   
8205                     0.0           1.0     1.0      1.0  ...   
127632                   0.0           1.0     1.0      1.0  ...   
32021                    0.0           0.0     1.0      1.0  ...   
...                      ...           ...     ...      ...  ...   
108360                   0.0           1.0     1.0      1.0  ...   
8531                     0.0           0.0     1.0      1.0  ...   
183429                   0.0           1.0     0.0      0.0  ...   
52932                    0.0           0.0     1.0      1.0  ...   
94566                    0.0           1.0     1.0      1.0  ...   

        AnyHealthcare  NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  \
235899            1.0          0.0      2.0       0.0       0.0       0.0   
74852             1.0          0.0      2.0       0.0       5.0       0.0   
8205              1.0          0.0      2.0       0.0       0.0       0.0   
127632            1.0          0.0      4.0       0.0       0.0       0.0   
32021             1.0          0.0      1.0       0.0       0.0       0.0   
...               ...          ...      ...       ...       ...       ...   
108360            0.0          1.0      1.0       7.0       0.0       0.0   
8531              1.0          0.0      3.0       0.0      30.0       1.0   
183429            1.0          0.0      4.0       0.0      30.0       0.0   
52932             1.0          0.0      4.0       0.0       5.0       1.0   
94566             1.0          0.0      3.0       0.0       0.0       0.0   

        Sex   Age  Education  Income  
235899  0.0  13.0        6.0     6.0  
74852   1.0   9.0        6.0     8.0  
8205    0.0  11.0        4.0     6.0  
127632  1.0  11.0        6.0     5.0  
32021   0.0  10.0        6.0     8.0  
...     ...   ...        ...     ...  
108360  0.0   6.0        5.0     6.0  
8531    0.0   9.0        4.0     1.0  
183429  0.0  10.0        4.0     7.0  
52932   0.0  10.0        6.0     3.0  
94566   0.0   8.0        6.0     8.0  

[63420 rows x 21 columns]

y_train


array([[0.],
       [0.],
       [0.],
       ...,
       [0.],
       [0.],
       [2.]])

y_test


array([[0.],
       [2.],
       [0.],
       ...,
       [0.],
       [2.],
       [0.]])

In [7]:
from pipeline_utilities_scrap import My_X_StandardScaler
from sklearn.preprocessing import StandardScaler

X_train_scaled, X_test_scaled = My_X_StandardScaler(X_train, X_test)


X_train_scaled


array([[-0.86656453, -0.8571917 ,  0.19740347, ..., -0.66518749,
         0.96397356,  0.93983593],
       [-0.86656453,  1.16660019,  0.19740347, ...,  0.97314934,
         0.96397356, -0.02488884],
       [-0.86656453, -0.8571917 ,  0.19740347, ..., -1.97585695,
         0.96397356, -0.98961362],
       ...,
       [-0.86656453,  1.16660019,  0.19740347, ..., -0.00985275,
         0.96397356,  0.45747354],
       [ 1.15398215,  1.16660019, -5.06576702, ..., -0.00985275,
         0.96397356, -2.43670079],
       [-0.86656453, -0.8571917 ,  0.19740347, ..., -0.33752012,
         0.96397356,  0.93983593]])

X_test_scaled


array([[-0.86656453, -0.8571917 ,  0.19740347, ..., -0.66518749,
        -1.06426621, -0.98961362],
       [ 1.15398215,  1.16660019,  0.19740347, ...,  0.64548198,
        -0.05014633, -0.50725123],
       [-0.86656453, -0.8571917 ,  0.19740347, ..., -0.99285485,
         0.96397356,  0.93983593],
       ...,
       [-0.86656453,  1.16660019,  0.19740347, ...,  1.30081671,
         0.96397356,  0.45747354],
       [ 1.15398215, -0.8571917 ,  0.19740347, ..., -0.66518749,
         0.96397356,  0.45747354],
       [-0.86656453,  1.16660019,  0.19740347, ...,  0.97314934,
        -1.06426621,  0.45747354]])

In [8]:
from sklearn.preprocessing import MinMaxScaler
from pipeline_utilities_scrap import My_MinMaxScaler

In [9]:
X_train_scaled, X_test_scaled = My_MinMaxScaler(X_train, X_test)

MinMax X_train:


array([[0.        , 0.        , 1.        , ..., 0.41666667, 1.        ,
        1.        ],
       [0.        , 1.        , 1.        , ..., 0.83333333, 1.        ,
        0.71428571],
       [0.        , 0.        , 1.        , ..., 0.08333333, 1.        ,
        0.42857143],
       ...,
       [0.        , 1.        , 1.        , ..., 0.58333333, 1.        ,
        0.85714286],
       [1.        , 1.        , 0.        , ..., 0.58333333, 1.        ,
        0.        ],
       [0.        , 0.        , 1.        , ..., 0.5       , 1.        ,
        1.        ]])

MinMax X_test:


array([[0.        , 0.        , 1.        , ..., 0.41666667, 0.6       ,
        0.42857143],
       [1.        , 1.        , 1.        , ..., 0.75      , 0.8       ,
        0.57142857],
       [0.        , 0.        , 1.        , ..., 0.33333333, 1.        ,
        1.        ],
       ...,
       [0.        , 1.        , 1.        , ..., 0.91666667, 1.        ,
        0.85714286],
       [1.        , 0.        , 1.        , ..., 0.41666667, 1.        ,
        0.85714286],
       [0.        , 1.        , 1.        , ..., 0.83333333, 0.6       ,
        0.85714286]])

In [10]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score
from pipeline_utilities_scrap import My_LinearRegression
from pipeline_utilities_scrap import r2_adj
from sklearn.model_selection import cross_val_score
import numpy as np


In [11]:
mse, r2 = My_LinearRegression(X_train, X_test, y_train, y_test)

mse: 0.40336435676138965
R2: 0.1697843590834921
root mean squared error:  0.6351097202542169
score:  1.0
Adjusted R2:  1.0
All scores: [0.17131442 0.17580035 0.16906907 0.17685892 0.17336054]
Mean score: 0.17328065870753506
Standard Deviation: 0.002855265338906768


AttributeError: 'numpy.float64' object has no attribute 'adj_score'

In [ ]:
from sklearn.linear_model import LogisticRegression


In [ ]:
logistic_regression_model = LogisticRegression()
lr_model = logistic_regression_model.fit(X_train, y_train)
testing_predections = lr_model.predict(X_test)
accuracy_score(y_test, testing_predections)


In [ ]:
print(f"Training Data Score: {lr_model.score(X_train, y_train)}")
print(f"Testing Data Score: {lr_model.score(X_test, y_test)}")
testing_predections
